version: '3'
services:
  nginx:
    image: nginx:latest
    ports:
      - 8090:80
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ../chapter:/var/www/html
    depends_on:
      - php

  php:
    build: ./php
    volumes:
      - ../chapter:/var/www/html
    depends_on:
      - db

  db:
    image: mysql:8.0
    ports:
      - 13306:3306
    volumes:
      - ./mysql/data:/var/lib/mysql
    environment:
        - MYSQL_ROOT_PASSWORD=root
        - MYSQL_DATABASE=test
        - MYSQL_USER=test
        - MYSQL_PASSWORD=test

  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    ports:
      - 8888:80
    depends_on:
      - db